spring.application.name=SkillMentorAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/skillmentor
spring.datasource.username=postgres
spring.datasource.password=skillmentor
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

# Tell Hibernate which SQL dialect to use
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in console (for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============ SERVER CONFIGURATION ============
server.port=8080
server.servlet.context-path=/api/v1

# ============ LOGGING ============
logging.level.root=INFO
logging.level.com.skillmentor=DEBUG